name: ExportAndroidSign
on:
  workflow_dispatch

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Generate signing files
        run: |
          echo "${{ secrets.KEYSTORE_JKS_B64 }}" | base64 -d > my-release-key.jks
          rm -f keystore.properties
          echo -e "storeFile=./my-release-key.jks\nstorePassword=${{ secrets.STORE_PASSWORD }}\nkeyAlias=${{ secrets.KEY_ALIAS }}\nkeyPassword=${{ secrets.KEY_PASSWORD }}" > keystore.properties
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: android‑sign‑archive
          path: |
            my-release-key.jks
            keystore.properties
